In [1]:
# This import registers the 3D projection, but is otherwise unused.
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401 unused import

import matplotlib.pyplot as plt
import numpy as np

# Fixing random state for reproducibility
np.random.seed(19680801)


fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
x, y = np.random.rand(2, 100) * 4

print(x)
print(y)

[2.80146922 2.97100324 2.83712004 2.26698209 3.91114133 2.82533938
 0.99166303 0.6315334  2.79079409 2.87982667 1.03097772 1.36618713
 3.87504467 2.77802839 1.86553304 2.81125078 2.0471435  3.71496548
 2.9590772  2.48975613 2.60618188 1.58723045 2.17295758 3.19959811
 2.88617891 1.18145592 0.64378352 0.82450206 0.53730155 1.92242007
 1.37008725 1.45187716 3.89167055 0.44377445 1.55305636 3.1322635
 3.89158904 1.93283842 1.34568442 2.26967614 0.19176604 1.55574812
 3.62521458 0.64407284 2.97448454 2.53189665 1.29672007 3.68950613
 0.94890575 3.29578228 3.00242856 0.45513781 3.38144498 3.69572852
 0.88334717 3.7322155  1.95599497 1.89887456 0.35666989 0.91979271
 2.86374964 1.98450465 3.06595751 3.58718929 3.08889207 3.70869715
 2.45860811 2.43625508 2.73873946 1.00405187 3.35135055 0.47446247
 3.18893897 3.79601707 0.59225151 3.62748794 3.1534933  3.07362337
 2.39398593 1.76858247 2.89215208 1.666473   0.90724158 1.81690936
 3.39177501 3.7466238  3.82414474 1.56837726 2.83329868 0.51806

In [2]:
hist, xedges, yedges = np.histogram2d(x, y, bins=4, range=[[0, 4], [0, 4]])
print(hist)
print(xedges)
print(yedges)

[[ 5.  5.  6.  5.]
 [ 8.  4.  5.  6.]
 [ 8.  4.  5. 11.]
 [ 5.  7.  4. 12.]]
[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4.]


In [4]:
xpos, ypos = np.meshgrid(xedges[:-1] + 0.25, yedges[:-1] + 0.25, indexing="ij")
print(xpos)
print(ypos)

[[0.25 0.25 0.25 0.25]
 [1.25 1.25 1.25 1.25]
 [2.25 2.25 2.25 2.25]
 [3.25 3.25 3.25 3.25]]
[[0.25 1.25 2.25 3.25]
 [0.25 1.25 2.25 3.25]
 [0.25 1.25 2.25 3.25]
 [0.25 1.25 2.25 3.25]]


In [5]:
xpos = xpos.ravel()
ypos = ypos.ravel()
zpos = 0
print(xpos)
print(ypos)

[0.25 0.25 0.25 0.25 1.25 1.25 1.25 1.25 2.25 2.25 2.25 2.25 3.25 3.25
 3.25 3.25]
[0.25 1.25 2.25 3.25 0.25 1.25 2.25 3.25 0.25 1.25 2.25 3.25 0.25 1.25
 2.25 3.25]


In [ ]:
# Construct arrays for the anchor positions of the 16 bars.


# Construct arrays with the dimensions for the 16 bars.
dx = dy = 0.5 * np.ones_like(zpos)
dz = hist.ravel()

ax.bar3d(xpos, ypos, zpos, dx, dy, dz, zsort='average')

plt.show()