In [39]:
import pandas as pd
import numpy as np
import glob
import re
from OrderNpersist import to_vecs
from numpy.linalg import norm
from itertools import combinations,product

In [33]:
files = glob.glob('/home/lau/Desktop/Thesis Stuff/Dens3/ACT_0.9996log.txt')[0]
df = pd.read_csv(files,sep = '\t',header = None,names = ['time','cellid','type','x', 'y','z'])

In [34]:
# convert to list of tracks : 
ids = df.cellid.unique()
tracks = [df[df.cellid == i][['x','y','z']].to_numpy() for i in ids]

In [35]:
print(len(tracks))
print(tracks[0].shape)

833
(500, 3)


In [36]:
r = 10

def order_radius(tracks,r):
    vec_tracks = np.array([to_vecs(t) for t in tracks])
    print(vec_tracks.shape)
    print()
    # list of order 
    orders = []
    for i in range(len(vec_tracks[0])):
        vecs_at_t = vec_tracks[:,i]
        # tuple vec wit position : 
        vec_pos = [(tracks[j][i],vecs_at_t[j]) for j in range(len(vecs_at_t))]
    #     print(tracks[0][0])
    #     print(tracks[0][1])
    #     print(vec_pos[0])
        # ignore 0 vectors : (nonmoving cells)
    #     print(len(vecs_at_t))
        vecs_at_t = [t for t in vecs_at_t if norm(t[1]) != 0]
        pairs = combinations(vec_pos,2)
        #print(list(pairs))

        # filter out pairs that out of radius : 
        pairs = [(v1,v2) for (v1,v2) in pairs if norm(v1[0] - v2[0]) < r]
#         for pair in pairs:
#             print(pair[0])
#             print(pair[1])
#             print('\n')
#         break
        cosines = [np.dot(v1[1],v2[1])/(norm(v1[1]) * norm(v2[1])) for (v1,v2) in pairs] #if list(v1) != list(v2)
        orders.append(np.average(cosines))
    return orders

#orders = order_radius(tracks,r)


In [37]:
def sort_on_coord(l,y):
    l.sort(key = lambda x: x[0][y])
    return l

In [38]:
def order_radius2(tracks,r,dim):
    # instead of working with a radius, devide 3d grit in to parts
    
    vec_tracks = np.array([to_vecs(t) for t in tracks])
    # list of order 
    orders = []
    for i in range(len(vec_tracks[0])):
        vecs_at_t = vec_tracks[:,i]
        # tuple vec wit position : 
        vec_pos = [(tracks[j][i],vecs_at_t[j]) for j in range(len(vecs_at_t))]
        # order on coordinates : 
        vec_pos.sort(key = lambda x: max(x[0]))
        #for bound in np.linspace(10,dim,r):
        # sum all vectors within cube
        max_c = 0
        indx = 0
        sum_vec = None
        for tup in vec_pos:
            sum_vec += tup[1]
            max_c = max(tup[0])
            if int(max_c) % r == 0:
                orders.append(sum_vec)
                sum_vec = None
            
            
        for v in vec_pos:
            print(v)
        break
        #vecs_at_t = [t for t in vecs_at_t if norm(t[1]) != 0]
        pairs = combinations(vec_pos,2)

        # filter out pairs that out of radius : 
        pairs = [(v1,v2) for (v1,v2) in pairs if norm(v1[0] - v2[0]) < r]
        cosines = [np.dot(v1[1],v2[1])/(norm(v1[1]) * norm(v2[1])) for (v1,v2) in pairs] #if list(v1) != list(v2)
        orders.append(np.average(cosines))
    return orders

orders = order_radius2(tracks,10)

(array([1.4966443 , 3.84563758, 1.2147651 ]), array([-0.1409396 , -0.42281879,  1.25503356]))
(array([0.08666667, 5.17333333, 5.48666667]), array([ 0.88022075, -4.2792936 ,  0.39412804]))
(array([3.78      , 0.77333333, 5.97333333]), array([-2.49052632, 46.85166667, -2.88780702]))
(array([5.81208054, 7.16107383, 7.12751678]), array([ 1.17458613,  0.99225951, -1.50085011]))
(array([8.09210526, 3.19736842, 0.55921053]), array([0.29715648, 1.7489403 , 0.48776934]))
(array([0.69536424, 8.23178808, 4.59602649]), array([47.90066225, -0.90066225,  0.52317881]))
(array([0.24832215, 1.77181208, 9.62416107]), array([2.19834452, 0.29485459, 0.63583893]))
(array([9.95973154, 2.89932886, 8.46979866]), array([1.61073826, 0.67785235, 1.11409396]))
(array([10.26      ,  4.88666667,  4.13333333]), array([ 1.68      ,  0.40666667, -0.03333333]))
(array([ 3.47019868,  9.8013245 , 10.90066225]), array([-2.70860927, -0.55629139,  0.36423841]))
(array([11.5033557 ,  9.33557047,  3.97986577]), array([ 2.9271

(array([21.81208054, 30.45637584, 44.36241611]), array([0.48993289, 1.91946309, 0.52348993]))
(array([44.37333333,  7.68666667, 32.33333333]), array([-1.31333333, -0.20666667,  0.79333333]))
(array([44.37583893,  9.66442953,  7.91946309]), array([0.69749441, 0.61557047, 1.93387025]))
(array([44.43708609,  5.45695364, 40.46357616]), array([ 0.29139073, -0.06622517, -0.78807947]))
(array([44.47651007, 20.46308725, 44.08053691]), array([ 1.29682327,  0.13691275, -3.08053691]))
(array([ 1.95302013,  7.12080537, 44.52348993]), array([1.89364653, 2.71252796, 1.61651007]))
(array([23.23489933, 44.69127517, 20.93288591]), array([ 2.118434  ,  2.0553915 , -1.97955257]))
(array([41.79865772, 44.71812081, 25.04026846]), array([ 1.62416107,  2.7852349 , -0.5704698 ]))
(array([ 6.41333333,  2.67333333, 44.76      ]), array([2.00666667, 2.66      , 0.62666667]))
(array([44.76666667,  0.68666667, 17.70666667]), array([-1.12      , -0.52666667,  3.66      ]))
(array([27.32450331,  7.50331126, 44.76821

NameError: name 'orders' is not defined

In [44]:
x = list(range(2000))
y = list(combinations(x,2))
print(len(y))

1999000
