In [1]:
for i in range(300):
    print(i%5)

0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4


In [1]:
from math import pi
import numpy as np
v = 500

def to_radius(v):
    r = (v/((4/3)*pi))**(1/3)
    return r

def to_volume(r):
    v = (4/3) * pi * r**3
    return v

def to_perimeter(r):
    return 4*pi*r**2

r = to_radius(150)
v = to_volume(r)
a = to_perimeter(r)
print(r,v,a)

3.2961038252544337 149.99999999999994 136.5248256296245


In [7]:
half_sphere = to_volume(5.5 * 300) / 2
cube = half_sphere**(1/3)
print(half_sphere,cube,cube**3)

9408284599.338032 2111.0741219452634 9408284599.338022


In [8]:
x  = np.log(cube)/np.log(2)
print(2**x,2**11)

2111.074121945264 2048


In [9]:
tot_vol = to_volume(7)
tot_vol/150

9.57836693494488

In [1]:
from numpy.linalg import norm
import numpy as np
x = np.array([1,3,4])
y = np.array([2,3,4])
print(norm(y-x))

1.0


In [11]:
x = np.array([[3, 4, 2], [1, 3, 1]])
index_array = np.argpartition(x, kth= 1, axis=None)[-3:]
print(index_array)
z = np.take_along_axis(x, index_array, axis=None)  # same as np.partition(x, kth=1)
print(set(z))
cntrs = []
for val in set(z):
    print(val)
    cords = np.where(x == val)
    print(cords)
    print()
    cntrs+= list(zip(*cords))

[0 4 1]
{3, 4}
3
(array([0, 1]), array([0, 1]))

4
(array([0]), array([1]))



In [12]:
x = np.array(cntrs)
type(x[0])
print(x)

[[0 0]
 [1 1]
 [0 1]]


In [13]:
l_act = np.linspace(0,1000,6)[1:]
l_act

array([ 200.,  400.,  600.,  800., 1000.])

In [14]:
x = 2
y = 4
z = 5
coords = [x,y,z]
#coords = coords - 96 
for i in range(len(cords)):
    coords[i] = coords[i] - 96
    if coords[i] < 0:
        coords[i] = 0
    if coords[i] > 64:
        coords[i] = 64
x,y,z = coords


In [15]:
print(x,y,z)

0 0 5


In [16]:
print(coords)

[0, 0, 5]


In [18]:
coords = [[1,3,4],[4,3,5]]
np.average(coords)

3.3333333333333335

In [3]:
 np.linspace(0,2000,11)[1:]

array([ 200.,  400.,  600.,  800., 1000., 1200., 1400., 1600., 1800.,
       2000.])

In [13]:
from itertools import product
l_act = np.linspace(0,2000,6)[1:]
max_act = np.linspace(10,100,10)
inputs = [(x[0],x[1]) for x in product(l_act,max_act)]
#jobs = []
print(len(inputs))
#exit()
inpts2 = []
for i in range(5):
    jobs = []
    #inpts = inputs[i*10:(i+1)*10-1]
    #print(i*10,(i+1)*10-1)
    inpts = inputs[i*10:(i+1)*10]
    inpts2 += (inpts)

50


In [14]:
for i in range(50):
    print(inputs[i],inpts2[i])

(400.0, 10.0) (400.0, 10.0)
(400.0, 20.0) (400.0, 20.0)
(400.0, 30.0) (400.0, 30.0)
(400.0, 40.0) (400.0, 40.0)
(400.0, 50.0) (400.0, 50.0)
(400.0, 60.0) (400.0, 60.0)
(400.0, 70.0) (400.0, 70.0)
(400.0, 80.0) (400.0, 80.0)
(400.0, 90.0) (400.0, 90.0)
(400.0, 100.0) (400.0, 100.0)
(800.0, 10.0) (800.0, 10.0)
(800.0, 20.0) (800.0, 20.0)
(800.0, 30.0) (800.0, 30.0)
(800.0, 40.0) (800.0, 40.0)
(800.0, 50.0) (800.0, 50.0)
(800.0, 60.0) (800.0, 60.0)
(800.0, 70.0) (800.0, 70.0)
(800.0, 80.0) (800.0, 80.0)
(800.0, 90.0) (800.0, 90.0)
(800.0, 100.0) (800.0, 100.0)
(1200.0, 10.0) (1200.0, 10.0)
(1200.0, 20.0) (1200.0, 20.0)
(1200.0, 30.0) (1200.0, 30.0)
(1200.0, 40.0) (1200.0, 40.0)
(1200.0, 50.0) (1200.0, 50.0)
(1200.0, 60.0) (1200.0, 60.0)
(1200.0, 70.0) (1200.0, 70.0)
(1200.0, 80.0) (1200.0, 80.0)
(1200.0, 90.0) (1200.0, 90.0)
(1200.0, 100.0) (1200.0, 100.0)
(1600.0, 10.0) (1600.0, 10.0)
(1600.0, 20.0) (1600.0, 20.0)
(1600.0, 30.0) (1600.0, 30.0)
(1600.0, 40.0) (1600.0, 40.0)
(1600.0, 50.0)

In [7]:
def return_bounds(dim):
    cube = np.zeros((dim,dim,dim))
    #set face of cube to 1:
    cube[0,:,:] = 1.
    cube[-1,:,:] = 1.
    cube[:,0,:] = 1.
    cube[:,-1,:] = 1.
    cube[:,:,0] = 1.
    cube[:,:,-1] = 1.
    return cube.astype(np.uint32)

dim = 10

cube = np.zeros((dim,dim,dim))
bounds = return_bounds(10)


In [8]:
cube[bounds == 1] =1

In [9]:
cube

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]