In [1]:
for i in range(300):
    print(i%5)

0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4
0
1
2
3
4


In [2]:
from math import pi
v = 500

def to_radius(v):
    r = (v/((4/3)*pi))**(1/3)
    return r

def to_volume(r):
    v = (4/3) * pi * r**3
    return v

def to_perimeter(r):
    return 4*pi*r**2

r = to_radius(150)
v = to_volume(r)
a = to_perimeter(r)
print(r,v,a)

3.2961038252544337 149.99999999999994 136.5248256296245


In [15]:
half_sphere = to_volume(5.5 * 300) / 2
cube = half_sphere**(1/3)
print(half_sphere,cube,cube**3)

9408284599.338032 2111.0741219452634 9408284599.338022


In [17]:
x  = np.log(cube)/np.log(2)
print(2**x,2**11)

2111.074121945264 2048 4096


In [21]:
tot_vol = to_volume(7)
tot_vol/150

9.57836693494488

In [3]:
from numpy.linalg import norm
import numpy as np
x = np.array([1,3,4])
y = np.array([2,3,4])
print(norm(y-x))

1.0


In [8]:
x = np.array([[3, 4, 2], [1, 3, 1]])
index_array = np.argpartition(x, kth= 1, axis=None)[-3:]
print(index_array)
z = np.take_along_axis(x, index_array, axis=None)  # same as np.partition(x, kth=1)
print(set(z))
cntrs = []
for val in set(z):
    print(val)
    cords = np.where(x == val)
    print(cords)
    print()
    cntrs+= list(zip(*cords))

[0 4 1]
{3, 4}
3
(array([0, 1]), array([0, 1]))

4
(array([0]), array([1]))



In [9]:
x = np.array(cntrs)
type(x[0])
print(x)

[[0 0]
 [1 1]
 [0 1]]


In [32]:
l_act = np.linspace(0,1000,6)[1:]
l_act

array([ 200.,  400.,  600.,  800., 1000.])